Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = os.path.join(str(Dir('#')), 'applications')

src = Split("""
application.c
startup.c
""")
if GetDepend('RT_USING_LIGHT_WAVE_CURER'):
    src += ['light_wave_curer_button.c','light_wave_curer_display.c','light_wave_curer_output.c']	

if GetDepend('RT_USING_CAN'):
    src += ['canapp.c']

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
