from building import *

cwd = GetCurrentDir()
src = [] 
CPPPATH = [cwd + '/../include']
group = []

if GetDepend(['RT_USING_HWADC']):
    src = src + ['hwadc.c']	

if len(src):
    group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
