from building import *

cwd = GetCurrentDir()
src = [] 
CPPPATH = [cwd + '/../include']
group = []

if GetDepend(['RT_USING_PIN']):
    src = src + ['pin.c']
if GetDepend(['RT_USING_HWBUTTON']):
    src = src + ['hwbutton.c']	
if GetDepend(['RT_USING_LCDHT1621B']):
    src = src + ['lcdht1621b.c']	
if GetDepend(['RT_USING_XT8XXP8']):
    src = src + ['xt8xxp8.c']		

if len(src):
    group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
