# RT-Thread building script for component

Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Split('''
Device/ST/STM32F1xx/Source/Templates/system_stm32f1xx.c
''')
CPPPATH = [cwd + '/Device/ST/STM32F1xx/Include', cwd + '/Include']
CPPDEFINES = [rtconfig.PART_TYPE] 

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
     folder = 'gcc'
elif rtconfig.CROSS_TOOL == 'keil':
     folder = 'arm'
elif rtconfig.CROSS_TOOL == 'iar':
     folder = 'iar'
#Device/ST/STM32F1xx/Source/Templates/iar/startup_stm32f103xe.s     
src += ['Device/ST/STM32F1xx/Source/Templates/arm/startup_stm32f103xe.s']

group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
